### ISSUE TITLE
Cannot NPM install on MAC

### ISSUE THREAD

**Issue by daMogli** [otalk/otalk-im-client#33]
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ayushgupta/otalk-im-client/node_modules/jxt/node_modules/ltx-dom-shim/node_modules/ltx/node_modules/node-expat
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ayushgupta/otalk-im-client/npm-debug.log

**Comment by micky2be** [comment]
Just to let you know that is due to the node version. You need to run it under Node 0.10.x
Would have been nice if they had specify the requirement though.

**Comment by potzkovge** [comment]
> Just to let you know that is due to the node version. You need to run it under Node 0.10.x
Would have been nice if they had specify the requirement though.

Fixed  the problem for me

**Comment by sonnyp** [comment]
@micky2be @potzkovge what node version were you using?

**Comment by sonnyp** [comment]
@legastero could you update ltx on jxt so it doesn't depend on node-expat anymore? let me know if I can help with something

**Comment by potzkovge** [comment]
Tried 0.12.x
and v4.3.1

both didn’t work.

**Comment by sonnyp** [comment]
@potzkovge thanks, updating ltx in jxt should solve the issue

**Comment by potzkovge** [comment]
great. i will test it once it's done

**Comment by sonnyp** [comment]
actually ltx is up to date on jxt the problem is otalk-im-client using an outdated jxt version

**Comment by potzkovge** [comment]
@sonnyp you might wanna look into stanza.io too the log also mentioned that. but i could build stanza.io and jxt separately
